@echo off
title Reiniciando Orbin Vite...
echo Matando procesos Vite anteriores...
taskkill /F /IM node.exe /T 2>nul
timeout /t 2 /nobreak >nul
echo Iniciando Vite con el fix del canvas...
cd /d "C:\Users\Azomarg\Documents\Claude_projects\Orbin\client"
start "Orbin Vite :5173" cmd /k "npx vite --port 5173 --force"
echo Esperando que Vite cargue...
timeout /t 5 /nobreak >nul
start "" "http://localhost:5173/app"
echo Done!
